{
 "title": "Cyrel",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Cyrel backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cyrel logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "10000", "sortDirection": "desc" }, "type": "logs" }
     ]
    }
   ]
  },
  {
   "title": "Requests to Cyrel backend with an aggregation of 5min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[5m])",
     "legendFormat": "[{{method}}] {{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Inbound traffic per minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_bytes_read_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outbound traffic per minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_bytes_written_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total inbound traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_bytes_read_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total outbound traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_bytes_written_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_connections_seconds_active_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registered users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cyrel_backend_registered_users_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cyrel sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_status_info", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Active jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_active_jobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total ran jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_ran_jobs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Next run of courses job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_courses_next_fire", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Next run of rooms job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scheduler_rooms_next_fire", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duration of tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scheduler_courses_duration_sum[5m])",
     "legendFormat": "courses job"
    },
    {
     "expr": "rate(scheduler_rooms_duration_sum[5m])",
     "legendFormat": "rooms job"
    },
    {
     "expr": "rate(scheduler_clean_course_duration_sum[5m])",
     "legendFormat": "clean courses job"
    }
   ]
  }
 ]
}